apiVersion: 1

datasources:
  - name: InfluxDB_Quantum
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: quantum_org
      defaultBucket: bot_metrics
    secureJsonData:
      token: my-super-secret-auth-token
